USE [HATC]
GO
SELECT IDENT_CURRENT 
DECLARE @Bronze varchar(100), @Silver varchar(100), @Gold varchar(100), @Platinum varchar(100), @Restricted varchar(100), @Banned varchar(100)  
SELECT @Bronze = Id FROM Ranks WHERE Name = 'Bronze'
SELECT @Silver = Id FROM Ranks WHERE Name = 'Silver'
SELECT @Gold = Id FROM Ranks WHERE Name = 'Gold'
SELECT @Restricted = Id FROM Ranks WHERE Name = 'Restricted'
SELECT @Banned = Id FROM Ranks WHERE Name = 'Banned'
INSERT INTO SessionItem (Name, Value, Source, IsAttunement, RarityId, IsCraftable)
VALUES

('Woodcutter''s Axe','WBW',0, @Silver,0),
('Witherbloom Primer','SCC',0, @Silver,0),
('Wingwear','PotA',0, @Bronze,0),
('Wings Of Flying','DMG',0, @Silver,0),
('Winged Boots','DMG',0, @Silver,0),
('Wind Fan','DMG',0, @Silver,0),
('Weird Tank','PA',0, @Silver,0),
('Weapon, +1','DMG',0, @Silver,0),
('Weapon of Certain Death','EGW',0, @Bronze,0),
('Wan,''Sheath', null,0,@Bronze,0),
('Wand Of Wonder','DMG',0, @Silver,0),
('Wand Of Winter','HDQ',0, @Silver,0),
('Wand Of Web','DMG',0, @Silver,0),
('Wand Of The War Mage +1','DMG',0, @Silver,0),
('Wand Of Secrets','DMG',0, @Silver,0),
('Wand Of Pyrotechnics','XGE',0, @Bronze,0),
('Wand Of Magic Missiles','DMG',0, @Silver,0),
('Wand Of Magic Detection','DMG',0, @Silver,0),
('Wand Of Entangle','TYP',0, @Silver,0),
('Wand Of Enemy Detection','DMG',0, @Silver,0),
('Wand Of Conducting','XGE',0, @Bronze,0),
('Walloping Ammunition','XGE',0, @Bronze,0),
('Vox Seeker','EGW',0, @Silver,0),
('Vicious Weapon (any weapon)','DMG',0, @Bronze,0),
('Vial of Thought Capture','GGR',0, @Silver,0),
('Veteran''s Cane','XGE',0, @Bronze,0),
('Ventilatin,''Lungs', null,0, @Silver,0),
('Vanrak''s Mithral Shirt (Attunment)','WDMM',0, @Silver,0),
('Universal Solvent','DMG',0, @Bronze,0),
('Unbreakable Arrow','XGE',0, @Silver,0),
('Trident Of Fish Command','DMG',0, @Silver,0),
('Treebane','CS',0, @Silver,0),
('Tentacle Rod','DMG',0, @Silver,0),
('Tankard Of Sobriety','XGE',0, @Bronze,0),
('Tankard of Plenty','HDQ',0, @Bronze,0),
('Talking Doll','XGE',0, @Bronze,0),
('Sword Of Wounding (any sword)','DMG',0, @Silver,0),
('Sword of the Crusader (aka Lost Sword)','CoS',0, @Silver,0),
('Sword Of Life Stealing (any sword)','DMG',0, @Silver,0),
('Strixhaven Pennant','SCC',0, @Bronze,0),
('Storm Boomerang','PA',0, @Bronze,0),
('Stonespeaker Crystal','OA',0, @Silver,0),
('Stone Of Good Luck (Luckstone)','DMG',0, @Silver,0),
('Staff Of Withering','DMG',0, @Silver,0),
('Staff of the Ivory Claw','EGW',0, @Silver,0),
('Staff Of The Adder','DMG',0, @Silver,0),
('Staff Of Flowers','XGE',0, @Bronze,0),
('Staff Of Birdcalls','XGE',0, @Bronze,0),
('Staff Of Adornment','XGE',0, @Bronze,0),
('Spies'' Murmur','GGR',0, @Silver,0),
('Spider Staff','LMP',0, @Silver,0),
('Spellwrought Tattoo (Cantrip)','TCE',0, @Bronze,0),
('Spellwrought Tattoo (5th level)','TCE',0, @Silver,0),
('Spellwrought Tattoo (4th level)','TCE',0, @Silver,0),
('Spellwrought Tattoo (3rd level)','TCE',0, @Silver,0),
('Spellwrought Tattoo (2nd level)','TCE',0, @Silver,0),
('Spellwrought Tattoo (1st level)','TCE',0, @Bronze,0),
('Spellshard','null',0, @Bronze,0),
('Spell Scroll (Level 5)','DMG',0, @Silver,0),
('Spell Scroll (Level 4)','DMG',0, @Bronze,0),
('Spell Scroll (Level 3)','DMG',0, @Bronze,0),
('Spell Scroll (Level 2)','DMG',0, @Bronze,0),
('Spell Scroll (Level 1)','DMG',0, @Bronze,0),
('Spell Scroll (Level 0)','DMG',0, @Bronze,0),
('Sovereign Glue','DMG',0, @Silver,0),
('Smoldering Armor','XGE',0, @Bronze,0),
('Slippers Of Spider Climbing','DMG',0, @Silver,0),
('Skyblinder Staff','GGR',0, @Silver,0),
('Siren Song Lyre','MOoT',0, @Silver,0),
('Silverquill Primer','SCC',0, @Silver,0),
('Shiftweave','ERLW',0, @Silver,0),
('Shield, +1','DMG',0, @Silver,0),
('Shield Of Missile Attraction','DMG',0, @Silver,0),
('Shield Of Expression','XGE',0, @Bronze,0),
('Shatterspike (longsword)','TYP',0, @Silver,0),
('Shadowfell Shard','TCE',0, @Silver,0),
('Shadowfell Brand Tattoo','TCE',0, @Silver,0),
('Serpent''s Fang','CM',0, @Silver,0),
('Sending Stones','DMG',0, @Silver,0),
('Sekolahian Worshiping Statuette','GoS',0, @Bronze,0),
('Seeker Dart','PA',0, @Bronze,0),
('Scroll Of Protection','DMG',0, @Bronze,0),
('Scribe''s Pen','null',0, @Bronze,0),
('Scissors of Shadow Snipping','WBW',0, @Bronze,0),
('Saddle Of The Cavalier','DMG',0, @Silver,0),
('Ruby Of The War Mage','XGE',0, @Silver,0),
('Rope Of Mending','XGE',0, @Bronze,0),
('Rope Of Entanglement','DMG',0, @Silver,0),
('Rope Of Climbing','DMG',0, @Silver,0),
('Rod Of The Vonindod','SKT',0, @Silver,0),
('Rod of Retribution','EGW',0, @Bronze,0),
('Robe Of Useful Items','DMG',0, @Silver,0),
('Robe Of Serpents','SKT',0, @Bronze,0),
('Ring Of X-Ray Vision','DMG',0, @Silver,0),
('Ring Of Water Walking','DMG',0, @Silver,0),
('Ring Of Warmth','DMG',0, @Silver,0),
('Ring Of Truth Telling','WDH',0, @Silver,0),
('Ring Of The Ram','DMG',0, @Silver,0),
('Ring of Temporal Salvation','EGW',0, @Silver,0),
('Ring Of Swimming','DMG',0, @Silver,0),
('Ring Of Resistance','DMG',0, @Silver,0),
('Ring Of Protection','DMG',0, @Silver,0),
('Ring of Obscuring','EGW',0, @Bronze,0),
('Ring Of Jumping','DMG',0, @Silver,0),
('Ring Of Feather Falling','DMG',0, @Silver,0),
('Ring Of Evasion','DMG',0, @Silver,0),
('Ring Of Animal Influence','DMG',0, @Silver,0),
('Reszur','PA',0, @Silver,0),
('Radiance','CM',0, @Silver,0),
('Quiver Of Ehlonna','DMG',0, @Silver,0),
('Quandrix Primer','SCC',0, @Silver,0),
('Quaals Feather Token (Whip)','DMG',0, @Bronze,0),
('Quaals Feather Token (Tree)','DMG',0, @Silver,0),
('Quaals Feather Token (Swan Boat)','DMG',0, @Silver,0),
('Quaals Feather Token (Fan)','DMG',0, @Bronze,0),
('Quaals Feather Token (Bird)','DMG',0, @Silver,0),
('Quaals Feather Token (Anchor)','DMG',0, @Bronze,0),
('Pyroconverger','GGR',0, @Silver,0),
('Psi Crystal','IDRotF',0, @Silver,0),
('Protective Verses','TCE',0, @Silver,0),
('Prosthetic Limb','TCE',0, @Bronze,0),
('Propeller Helm','DMM',0, @Bronze,0),
('Professor Orb','DMM',0, @Silver,0),
('Prismari Primer','SCC',0, @Silver,0),
('Potion Of Water Breathing','DMG',0, @Bronze,0),
('Potion Of Watchful Rest','WDH',0, @Bronze,0),
('Potion Of Resistance','DMG',0, @Bronze,0),
('Potion Of Mind Reading','DMG',0, @Bronze,0),
('Potion Of Mind Control (Humanoid)','TYP',0, @Silver,0),
('Potion Of Mind Control (Beast)','TYP',0, @Bronze,0),
('Potion of Maximum Power','EGW',0, @Bronze,0),
('Potion Of Invulnerability','DMG',0, @Silver,0),
('Potion Of Invisibility','DMG',0, @Silver,0),
('Potion Of Heroism','DMG',0, @Bronze,0),
('Potion of Healing (Superior)','DMG',0, @Silver,0),
('Potion Of Healing (Greater)','DMG',0, @Bronze,0),
('Potion Of Healing','DMG',0, @Bronze,0),
('Potion Of Growth','DMG',0, @Bronze,0),
('Potion Of Giant Strength (Hill)','DMG',0, @Silver,0),
('Potion Of Gaseous Form','DMG',0, @Bronze,0),
('Potion Of Fire Breath','DMG',0, @Bronze,0),
('Potion Of Diminution','DMG',0, @Bronze,0),
('Potion Of Comprehension','WDH',0, @Bronze,0),
('Potion Of Climbing','DMG',0, @Bronze,0),
('Potion Of Clairvoyance','DMG',0, @Silver,0),
('Potion of Aqueous Form','MOoT',0, @Bronze,0),
('Potion Of Animal Friendship','DMG',0, @Bronze,0),
('Potion of Advantage','WBW',0, @Bronze,0),
('Pot Of Awakening','XGE',0, @Bronze,0),
('Portable Hole','DMG',0, @Silver,0),
('Pole Of Collapsing','XGE',0, @Bronze,0),
('Pole Of Angling','XGE',0, @Bronze,0),
('Planecaller''s Codex','TCE',0, @Silver,0),
('Planar Key', 'AFR,HP',0, @Silver,0),
('Pixie Dust','WBW',0, @Bronze,0),
('Piwafwi Of Fire Resistance','OA',0, @Silver,0),
('Piwafwi (Cloak Of Elvenkind)','OA',0, @Silver,0),
('Pipes Of The Sewers','DMG',0, @Silver,0),
('Pipes Of Haunting','DMG',0, @Silver,0),
('Pipe Of Smoke Monsters','XGE',0, @Bronze,0),
('Pipe Of Remembrance','GoS',0, @Bronze,0),
('Piercer','AI',0, @Silver,0),
('Periapt Of Wound Closure','DMG',0, @Silver,0),
('Periapt Of Health','DMG',0, @Silver,0),
('Perfume Of Bewitching','XGE',0, @Bronze,0),
('Pearl of Undead Detection','DMM',0, @Bronze,0),
('Pearl Of Power','DMG',0, @Silver,0),
('Pathfinder''s Axe','PA',0, @Silver,0),
('Paper Bird (five)','WDH',0, @Bronze,0),
('Outer Essence Shard','TCE',0, @Silver,0),
('Orb Of Time','XGE',0, @Bronze,0),
('Orb Of The Stein Rune','SKT',0, @Silver,0),
('Orb O', 'Shielding',0, @Bronze,0),
('Orb Of Gonging','DMM',0, @Bronze,0),
('Orb Of Direction','XGE',0, @Bronze,0),
('Opal Of The Ild Rune','SKT',0, @Silver,0),
('Oil Of Slipperiness','DMG',0, @Bronze,0),
('Oil Of Etherealness','DMG',0, @Silver,0),
('Night Caller','TYP',0, @Silver,0),
('Needle of Mending','EGW',0, @Silver,0),
('Necklace of Fireballs','DMG',0, @Silver,0),
('Necklace Of Adaptation','DMG',0, @Silver,0),
('Nature''s Mantle','TCE',0, @Silver,0),
('Mystery Key','XGE',0, @Bronze,0),
('Mummy Rot Antidote','IMR',0, @Bronze,0),
('Moon-Touched Sword','XGE',0, @Silver,0),
('Moodmark Paint','GGR',0, @Bronze,0),
('Molten Bronze Skin','MOoT',0, @Silver,0),
('Mizzium Apparatus','GGR',0, @Silver,0),
('Mithral Armor (medium or heavy, not hide)','DMG',0, @Silver,0),
('Medallion Of Thoughts','DMG',0, @Silver,0),
('Masquerade Tattoo','TCE',0, @Bronze,0),
('Masque Charm','SCC',0, @Bronze,0),
('Mask Of The Beast','ToA',0, @Bronze,0),
('Mariner''s Armor','DMG',0, @Silver,0),
('Macuahuitl','TftyP',0, @Silver,0),
('Mace Of Terror','DMG',0, @Silver,0),
('Mace Of Smiting','DMG',0, @Silver,0),
('Mace Of Disruption','DMG',0, @Silver,0),
('Lyre of Building','TCE',0, @Silver,0),
('Lorehold Primer','SCC',0, @Silver,0),
('Lock Of Trickery','XGE',0, @Bronze,0),
('Living Gloves','ERLW',0, @Silver,0),
('Lightbringer','LMP',0, @Silver,0),
('Libram of Souls and Flesh','TCE',0, @Silver,0),
('Lantern of Tracking','ID',0, @Bronze,0),
('Lantern Of Revealing','DMG',0, @Silver,0),
('Knave''s Eye Patch','WDH',0, @Silver,0),
('Keycharm', null, 0, @Bronze,0),
('Keoghtom''s Ointment (Per jar) (AKA "Restorative Ointment")','DMG',0, @Bronze,0),
('Junky +1 Dagger','TYP',0, @Bronze,0),
('Javelin Of Lightning','DMG',0, @Silver,0),
('Jade Serpent Staff','DMM',0, @Silver,0),
('Iron Bands Of Bilarro (AKA Iron Bands Of Binding)','DMG',0, @Silver,0),
('Ioun Stone Of Supreme Intellect','LLK',0, @Silver,0),
('Ioun Stone Of Self Preservation','LLK',0, @Silver,0),
('Ioun Stone Of Religious Knowledge','LLK',0, @Silver,0),
('Ioun Stone Of Natural Knowledge','LLK',0, @Silver,0),
('Ioun Stone Of Language Knowledge','LLK',0, @Silver,0),
('Ioun Stone Of Historical Knowledge','LLK',0, @Silver,0),
('Ioun Stone (Sustenance)','DMG',0, @Silver,0),
('Ioun Stone (Reserve)','DMG',0, @Silver,0),
('Ioun Stone (Protection)','DMG',0, @Silver,0),
('Instrument Of Scribing','XGE',0, @Bronze,0),
('Instrument Of Illusions','XGE',0, @Bronze,0),
('Insignia Of Claws','HDQ',0, @Silver,0),
('Immovable Rod','DMG',0, @Silver,0),
('Imbued Woo Focus', null, 0, @Bronze,0),
('Illuminator''s Tattoo','TCE',0, @Bronze,0),
('Horseshoes Of Speed','DMG',0, @Silver,0),
('Horn Of Silent Alarm','XGE',0, @Bronze,0),
('Horn Of Blasting','DMG',0, @Bronze,0),
('Hook of Fisher''s Delight','IDRotF',0, @Silver,0),
('Heward''s Handy Spice Pouch','XGE',0, @Bronze,0),
('Heward''s Handy Haversack','DMG',0, @Silver,0),
('Hew','LMP',0, @Silver,0),
('Helm Of Underwater Action','GoS',0, @Silver,0),
('Helm Of Comprehending Languages','DMG',0, @Bronze,0),
('Heart Weaver''s Primer','TCE',0, @Silver,0),
('Hat Of Wizardry','XGE',0, @Bronze,0),
('Hat Of Vermin','XGE',0, @Bronze,0),
('Hat Of Disguise','DMG',0, @Silver,0),
('Gulthias Staff','CS',0, @Silver,0),
('Guardian Emblem','TCE',0, @Silver,0),
('Green Copper Ewer','CoS',0, @Silver,0),
('Goggles of Object Reading','EGW',0, @Bronze,0),
('Goggles Of Night','DMG',0, @Silver,0),
('Gnomengard Grenade','DC',0, @Silver,0),
('Gloves Of Thievery','DMG',0, @Silver,0),
('Gloves Of Swimming And Climbing','DMG',0, @Silver,0),
('Gloves Of Missile Snaring','DMG',0, @Silver,0),
('Glamerweave (Uncomm,n)', null ,0, @Silver,0),
('Glamerweave (Common)','WGE',0, @Bronze,0),
('Giant Slayer (any sword or axe)','DMG',0, @Silver,0),
('Ghost Lantern','TA',0, @Silver,0),
('Gem Of Brightness','DMG',0, @Silver,0),
('Gauntlets Of Flaming Fury','BGA',0, @Silver,0),
('Galder''s Bubble Pipe','LLK',0, @Bronze,0),
('Fulminating Treatise','TCE',0, @Silver,0),
('Flying Chariot','MOoT',0, @Silver,0),
('Flame Tongue Shortsword of Greed','TYP',0, @Silver,0),
('Flame Tongue','DMG',0, @Silver,0),
('Figurine of Wondrous Power (Silver Raven)','DMG',0, @Silver,0),
('Figurine of Wondrous Power (Serpentine Owl)','DMG',0, @Silver,0),
('Figurine of Wondrous Power (Onyx Dog)','DMG',0, @Silver,0),
('Figurine of Wondrous Power (Marble Elephant)','DMG',0, @Silver,0),
('Figurine of Wondrous Power (Ebony Fly)','DMG',0, @Silver,0),
('Figurine of Wondrous Power (Bronze Griffon)','DMG',0, @Silver,0),
('Feywild Shard','TCE',0, @Silver,0),
('Feather Token (Feather Fa,l)', null ,0, @Silver,0),
('Feather Of Diatryma Summoning','WDH',0, @Silver,0),
('Far Realm Shard','TCE',0, @Silver,0),
('Failed Experiment Wand','AI',0, @Silver,0),
('E0 Of The Eagle','DMG',0, @Silver,0),
('E0 Of Minute Seeing','DMG',0, @Silver,0),
('E0 Of Charming','DMG',0, @Silver,0),
('Eversmoking Bottle','DMG',0, @Silver,0),
('Everbrigh Lantern', null, 0, @Bronze,0),
('Ersatz Eye','XGE',0, @Bronze,0),
('Enduring Spellbook','XGE',0, @Bronze,0),
('Emerald Pen','FTD',0, @Bronze,0),
('Elven Chain','DMG',0, @Silver,0),
('Elixir Of Health','DMG',0, @Bronze,0),
('Elemental Essence Shard','TCE',0, @Silver,0),
('Eldritch Claw Tattoo','TCE',0, @Silver,0),
('Elder Cartographers Glossography','AI',0, @Bronze,0),
('Earworm', null, 0, @Silver,0),
('Ear Horn Of Hearing','XGE',0, @Bronze,0),
('Eagle Whistle','TYP',0, @Silver,0),
('Dust Of Dryness (1 pellet)','DMG',0, @Bronze,0),
('Dust Of Disappearance','DMG',0, @Silver,0),
('Dust of Deliciousness','EGW',0, @Bronze,0),
('Duplicitous Manuscript','TCE',0, @Silver,0),
('Driftglobe','DMG',0, @Silver,0),
('Dread Helm','XGE',0, @Bronze,0),
('Dragonhide Belt +1','FTD',0, @Silver,0),
('Dragongleam','HDQ',0, @Silver,0),
('Dragon Wing Bow','FTD',0, @Silver,0),
('Dragon Thighbone Club (only usable by huge creatures)','SKT',0, @Silver,0),
('Dragon Slayer (any sword)','DMG',0, @Silver,0),
('Dragon Sensing Longsword','PA',0, @Silver,0),
('Draconic Longsword','TA',0, @Bronze,0),
('Dodecahedron Of Doom','DMM',0, @Bronze,0),
('Docent', null, 0, @Silver,0),
('Dimensional Shackles','DMG',0, @Silver,0),
('Devotee''s Censer','TCE',0, @Silver,0),
('Deck Of Illusions','DMG',0, @Silver,0),
('Dark Shard Amulet','XGE',0, @Bronze,0),
('Dancing Monkey Fruit (1 fruit)','TA',0, @Bronze,0),
('Dagger Of Venom','DMG',0, @Silver,0),
('Dagger of Guitar Solos','DMM',0, @Bronze,0),
('Dagger Of Blindsight','DMM',0, @Silver,0),
('Cuddly Strixhaven Mascot','SCC',0, @Bronze,0),
('Crystal Blade','FTD',0, @Silver,0),
('Cracked Driftglobe','CM',0, @Bronze,0),
('Corpse Slayer','EGW',0, @Silver,0),
('Conch of Safe Rest','TP',0, @Bronze,0),
('College Primer','SCC',0, @Silver,0),
('Coin of Delving','EGW',0, @Bronze,0),
('Coiling Grasp Tattoo','TCE',0, @Silver,0),
('Clothes Of Mending','XGE',0, @Bronze,0),
('Clockwork Dog','SKT',0, @Bronze,0),
('Clockwork Amulet','XGE',0, @Silver,0),
('Cloak Of The Manta Ray','DMG',0, @Silver,0),
('Cloak Of The Bat','DMG',0, @Silver,0),
('Cloak Of Protection','DMG',0, @Silver,0),
('Cloak Of Many Fashions','XGE',0, @Bronze,0),
('Cloak Of Elvenkind','DMG',0, @Silver,0),
('Cloak Of Billowing','XGE',0, @Bronze,0),
('Cleansing Stone', null, 0, @Bronze,0),
('Claws Of The Umber Hulk','PA',0, @Bronze,0),
('Circlet Of Human Perfection','DMM',0, @Silver,0),
('Circlet Of Blasting','DMG',0, @Silver,0),
('Chromatic Rose','WBW',0, @Silver,0),
('Chime Of Opening','DMG',0, @Silver,0),
('Chest Of Preserving','DMM',0, @Bronze,0),
('Charm Of Plant Command','GoS',0, @Bronze,0),
('Charlatan''s Die','XGE',0, @Bronze,0),
('Cast Off Armor','XGE',0, @Bronze,0),
('Cap Of Water Breathing','DMG',0, @Silver,0),
('Candle Of The Deep','XGE',0, @Bronze,0),
('Candle Mace','BGA',0, @Silver,0),
('Butchers Bib','EGW',0, @Silver,0),
('Brooch Of Shielding','DMG',0, @Silver,0),
('Brooch of Living Essence','EGW',0, @Bronze,0),
('Bridle of Capturing','IMR',0, @Bronze,0),
('Breathing Bubble','EGW',0, @Bronze,0),
('Bracers Of Defense','DMG',0, @Silver,0),
('Bracers Of Archery','DMG',0, @Silver,0),
('Bracer Of Flying Daggers','WDH',0, @Silver,0),
('Bottled Breath','PA',0, @Bronze,0),
('Bottle of Boundless Coffee','SCC',0, @Bronze,0),
('Boots Of Striding And Springing','DMG',0, @Silver,0),
('Boots Of Speed','DMG',0, @Silver,0),
('Boots Of Levitation','DMG',0, @Silver,0),
('Boots Of False Tracks','XGE',0, @Bronze,0),
('Boots Of Elvenkind','DMG',0, @Silver,0),
('Bonecounter','SDW',0, @Silver,0),
('Bob','ToA',0, @Silver,0),
('Blood of the Lycanthrope Antidote','IMR',0, @Bronze,0),
('Bell Branch','TCE',0, @Silver,0),
('Bead of Refreshment','XGE',0, @Bronze,0),
('Bead of 0urishment','XGE',0, @Bronze,0),
('Bead Of Force','DMG',0, @Silver,0),
('Battering Shield','EGW',0, @Silver,0),
('Barrier Tattoo (15+DEX, max of 17)','TCE',0, @Silver,0),
('Barrier Tattoo (12+DEX)','TCE',0, @Bronze,0),
('Balloon Pack','PA',0, @Bronze,0),
('Balance Of Harmony','TYP',0, @Silver,0),
('Bag Of Holding','DMG',0, @Silver,0),
('Atlas of Endless Horizons','TCE',0, @Silver,0),
('Astromancy Archive','TCE',0, @Silver,0),
('Astral Shard','TCE',0, @Silver,0),
('Arrow-Catching Shield','DMG',0, @Silver,0),
('Armor Of Resistance','DMG',0, @Silver,0),
('Armor Of Gleaming (any medium or heavy)','XGE',0, @Bronze,0),
('Armblade', null, 0, @Bronze,0),
('Arcane Propulsion Arm','ERLW',0,@Silver,0),
('Arcanaloth''s Music Box','TA',0, @Bronze,0),
('Amulet of the Drunkard','EGW',0, @Bronze,0),
('Amulet Of Protection From Turning','TYP',0, @Silver,0),
('Ammunition +2 (20)','DMG',0, @Silver,0),
('Ammunition +1 (20)','DMG',0, @Bronze,0),
('Amber Runestone', 'NRH,LT',0, @Silver,0),
('Alchemy Jug','DMG',0, @Silver,0),
('Alchemical Compendium','TCE',0, @Silver,0),
('Adamantine Armor','DMG',0, @Silver,0),
('Acheron Blade','EGW',0, @Silver,0)
GO