// <auto-generated />
using System;
using HATC_CapstoneProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HATC_CapstoneProject.Migrations
{
    [DbContext(typeof(HavenDbContext))]
    partial class HavenDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HATC_CapstoneProject.Models.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Benefit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DowntimeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMasked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("bit");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DowntimeId");

                    b.HasIndex("LevelId");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.AchievementAdvancement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AchieveId")
                        .HasColumnType("int");

                    b.Property<int>("Advancement")
                        .HasColumnType("int");

                    b.Property<int?>("SessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AchieveId");

                    b.HasIndex("SessionId");

                    b.ToTable("AchievementAdvancement");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.AchievementProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AchievementId")
                        .HasColumnType("int");

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Goal")
                        .HasColumnType("int");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.ToTable("AchievementProgress");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Downtime")
                        .HasColumnType("int");

                    b.Property<int>("Exp")
                        .HasColumnType("int");

                    b.Property<int>("FactionPointsId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("SessionId")
                        .HasColumnType("int");

                    b.Property<bool>("isRetired")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FactionPointsId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SessionId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.Downtime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Downtime");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.DowntimeTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DowntimeId")
                        .HasColumnType("int");

                    b.Property<bool>("HasHead")
                        .HasColumnType("bit");

                    b.Property<bool>("IsComplication")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DowntimeId");

                    b.ToTable("DowntimeTable");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.DowntimeTableRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DowntimeTableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DowntimeTableId");

                    b.ToTable("DowntimeTableRow");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.Faction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Factions");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.FactionCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("SessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("FactionCard");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.FactionCardEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FacId")
                        .HasColumnType("int");

                    b.Property<int?>("FactionCardId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacId");

                    b.HasIndex("FactionCardId");

                    b.ToTable("FactionCardEntry");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.FactionPerk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FactionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Renown")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.ToTable("FactionPerk");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.FactionShop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<int?>("FactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.ToTable("FactionShop");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.NPC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apperance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Background")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FactionId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motivation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Personality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quirk")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.ToTable("NPC");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.Player", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscordName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PasswordReset")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PreferedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pronouns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.RPEXP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharId")
                        .HasColumnType("int");

                    b.Property<int?>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("TraitResolved")
                        .HasColumnType("int");

                    b.Property<bool>("isResolved")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CharId");

                    b.HasIndex("SessionId");

                    b.ToTable("RPEXP");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.Rank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BgColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ranking")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ranks");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DowntimeReward")
                        .HasColumnType("int");

                    b.Property<int>("GMCharacterId")
                        .HasColumnType("int");

                    b.Property<string>("InGameDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RealDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GMCharacterId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.SessionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SessionId")
                        .HasColumnType("int");

                    b.Property<int?>("SessionId1")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("SessionId1");

                    b.ToTable("SessionItem");

                    b.HasDiscriminator<string>("Discriminator").HasValue("SessionItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.StringListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DowntimeId")
                        .HasColumnType("int");

                    b.Property<int?>("DowntimeId1")
                        .HasColumnType("int");

                    b.Property<int?>("FactionShopId")
                        .HasColumnType("int");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NPCId")
                        .HasColumnType("int");

                    b.Property<int?>("NPCId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DowntimeId");

                    b.HasIndex("DowntimeId1");

                    b.HasIndex("FactionShopId");

                    b.HasIndex("NPCId");

                    b.HasIndex("NPCId1");

                    b.ToTable("StringListItem");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.TableListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DowntimeTableRowId")
                        .HasColumnType("int");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DowntimeTableRowId");

                    b.ToTable("TableListItem");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.Trigger", b =>
                {
                    b.Property<int>("TriggerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TriggerId"));

                    b.Property<string>("Accomidation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TriggerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Trigger");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.Item", b =>
                {
                    b.HasBaseType("HATC_CapstoneProject.Models.SessionItem");

                    b.Property<string>("Fate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SessionId2")
                        .HasColumnType("int");

                    b.HasIndex("SessionId2");

                    b.ToTable("SessionItem", t =>
                        {
                            t.Property("SessionId2")
                                .HasColumnName("Item_SessionId2");
                        });

                    b.HasDiscriminator().HasValue("Item");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.Monster", b =>
                {
                    b.HasBaseType("HATC_CapstoneProject.Models.SessionItem");

                    b.Property<int?>("SessionId2")
                        .HasColumnType("int");

                    b.HasIndex("SessionId2");

                    b.HasDiscriminator().HasValue("Monster");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.ShopItem", b =>
                {
                    b.HasBaseType("HATC_CapstoneProject.Models.SessionItem");

                    b.Property<string>("BanReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAttunement")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCraftable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShoppable")
                        .HasColumnType("bit");

                    b.Property<string>("LinkTo5eTools")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManualWeight")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceAdjustment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RarityId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("RarityId");

                    b.HasDiscriminator().HasValue("ShopItem");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.Achievement", b =>
                {
                    b.HasOne("HATC_CapstoneProject.Models.Downtime", null)
                        .WithMany("Achievements")
                        .HasForeignKey("DowntimeId");

                    b.HasOne("HATC_CapstoneProject.Models.Rank", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.AchievementAdvancement", b =>
                {
                    b.HasOne("HATC_CapstoneProject.Models.Achievement", "Achieve")
                        .WithMany()
                        .HasForeignKey("AchieveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HATC_CapstoneProject.Models.Session", null)
                        .WithMany("Achievements")
                        .HasForeignKey("SessionId");

                    b.Navigation("Achieve");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.AchievementProgress", b =>
                {
                    b.HasOne("HATC_CapstoneProject.Models.Achievement", null)
                        .WithMany("AchievementProgress")
                        .HasForeignKey("AchievementId");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.Character", b =>
                {
                    b.HasOne("HATC_CapstoneProject.Models.FactionCard", "FactionPoints")
                        .WithMany()
                        .HasForeignKey("FactionPointsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HATC_CapstoneProject.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HATC_CapstoneProject.Models.Session", null)
                        .WithMany("Characters")
                        .HasForeignKey("SessionId");

                    b.Navigation("FactionPoints");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.DowntimeTable", b =>
                {
                    b.HasOne("HATC_CapstoneProject.Models.Downtime", null)
                        .WithMany("Tables")
                        .HasForeignKey("DowntimeId");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.DowntimeTableRow", b =>
                {
                    b.HasOne("HATC_CapstoneProject.Models.DowntimeTable", null)
                        .WithMany("Table")
                        .HasForeignKey("DowntimeTableId");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.FactionCard", b =>
                {
                    b.HasOne("HATC_CapstoneProject.Models.Session", null)
                        .WithMany("FactionRenown")
                        .HasForeignKey("SessionId");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.FactionCardEntry", b =>
                {
                    b.HasOne("HATC_CapstoneProject.Models.Faction", "Fac")
                        .WithMany()
                        .HasForeignKey("FacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HATC_CapstoneProject.Models.FactionCard", null)
                        .WithMany("FactionPoints")
                        .HasForeignKey("FactionCardId");

                    b.Navigation("Fac");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.FactionPerk", b =>
                {
                    b.HasOne("HATC_CapstoneProject.Models.Faction", null)
                        .WithMany("Perks")
                        .HasForeignKey("FactionId");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.FactionShop", b =>
                {
                    b.HasOne("HATC_CapstoneProject.Models.Faction", null)
                        .WithMany("Shops")
                        .HasForeignKey("FactionId");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.NPC", b =>
                {
                    b.HasOne("HATC_CapstoneProject.Models.Faction", null)
                        .WithMany("Members")
                        .HasForeignKey("FactionId");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.RPEXP", b =>
                {
                    b.HasOne("HATC_CapstoneProject.Models.Character", "Char")
                        .WithMany()
                        .HasForeignKey("CharId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HATC_CapstoneProject.Models.Session", null)
                        .WithMany("RolePlayExp")
                        .HasForeignKey("SessionId");

                    b.Navigation("Char");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.Session", b =>
                {
                    b.HasOne("HATC_CapstoneProject.Models.Character", "GMCharacter")
                        .WithMany()
                        .HasForeignKey("GMCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GMCharacter");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.SessionItem", b =>
                {
                    b.HasOne("HATC_CapstoneProject.Models.Session", null)
                        .WithMany("AdHocItems")
                        .HasForeignKey("SessionId");

                    b.HasOne("HATC_CapstoneProject.Models.Session", null)
                        .WithMany("TreasureList")
                        .HasForeignKey("SessionId1");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.StringListItem", b =>
                {
                    b.HasOne("HATC_CapstoneProject.Models.Downtime", null)
                        .WithMany("Resolution")
                        .HasForeignKey("DowntimeId");

                    b.HasOne("HATC_CapstoneProject.Models.Downtime", null)
                        .WithMany("Resources")
                        .HasForeignKey("DowntimeId1");

                    b.HasOne("HATC_CapstoneProject.Models.FactionShop", null)
                        .WithMany("List")
                        .HasForeignKey("FactionShopId");

                    b.HasOne("HATC_CapstoneProject.Models.NPC", null)
                        .WithMany("AdventureHooks")
                        .HasForeignKey("NPCId");

                    b.HasOne("HATC_CapstoneProject.Models.NPC", null)
                        .WithMany("Interactions")
                        .HasForeignKey("NPCId1");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.TableListItem", b =>
                {
                    b.HasOne("HATC_CapstoneProject.Models.DowntimeTableRow", null)
                        .WithMany("Row")
                        .HasForeignKey("DowntimeTableRowId");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.Trigger", b =>
                {
                    b.HasOne("HATC_CapstoneProject.Models.Player", null)
                        .WithMany("Triggers")
                        .HasForeignKey("PlayerId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HATC_CapstoneProject.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HATC_CapstoneProject.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HATC_CapstoneProject.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HATC_CapstoneProject.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.Item", b =>
                {
                    b.HasOne("HATC_CapstoneProject.Models.Session", null)
                        .WithMany("Loot")
                        .HasForeignKey("SessionId2");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.Monster", b =>
                {
                    b.HasOne("HATC_CapstoneProject.Models.Session", null)
                        .WithMany("CombatItems")
                        .HasForeignKey("SessionId2");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.ShopItem", b =>
                {
                    b.HasOne("HATC_CapstoneProject.Models.Rank", "Rarity")
                        .WithMany()
                        .HasForeignKey("RarityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rarity");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.Achievement", b =>
                {
                    b.Navigation("AchievementProgress");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.Downtime", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("Resolution");

                    b.Navigation("Resources");

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.DowntimeTable", b =>
                {
                    b.Navigation("Table");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.DowntimeTableRow", b =>
                {
                    b.Navigation("Row");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.Faction", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Perks");

                    b.Navigation("Shops");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.FactionCard", b =>
                {
                    b.Navigation("FactionPoints");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.FactionShop", b =>
                {
                    b.Navigation("List");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.NPC", b =>
                {
                    b.Navigation("AdventureHooks");

                    b.Navigation("Interactions");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.Player", b =>
                {
                    b.Navigation("Triggers");
                });

            modelBuilder.Entity("HATC_CapstoneProject.Models.Session", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("AdHocItems");

                    b.Navigation("Characters");

                    b.Navigation("CombatItems");

                    b.Navigation("FactionRenown");

                    b.Navigation("Loot");

                    b.Navigation("RolePlayExp");

                    b.Navigation("TreasureList");
                });
#pragma warning restore 612, 618
        }
    }
}
